# User configuration file
# Important for initial setup
# The first three are needed for the project-pages theme.
plugins:
  - jekyll-seo-tag        # Easy SEO
  - jekyll-remote-theme   # So we can use the theme
  - jekyll-default-layout # So we can use the theme easily
  # If you have additional plugins, you can add them here.
  # Make sure GitHub supports them here: https://pages.github.com/versions/

# Don't change! (or do change if you really want ig)
remote_theme: BuildingAtom/project-pages@v1.2-theme

# Metadata and SEO-helper stuff
# This title here should correspond to your base site or as a shared title
title: Differentiable Discrete Elastic Rods for Real-Time Modeling of Deformable Linear Objects
url: "https://roahmlab.github.io"
baseurl: "/DEFORM"   # the subpath of your site, e.g. /blog
# This sets window title, not the title you read on the page
title-format: page-site # options are page-site, page, site.
lang: en

# Shenanigans from the template default because that's actually not a thing.
credit:
  copyright-symbol: false
  text: >- # supports markdown
    [Project pages template](https://www.github.com/BuildingAtom/project-pages)
    built by Adam Li / [@BuildingAtom](https://www.github.com/BuildingAtom)

# Hide the credits in the footer by setting this false.
show-credit: false
